// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycqJFvwlBHGV95O4oopQkDFAdRpNWtJI',
    appId: '1:869470742871:web:2645e3101dc71770baf612',
    messagingSenderId: '869470742871',
    projectId: 'newapp-8d36b',
    authDomain: 'newapp-8d36b.firebaseapp.com',
    storageBucket: 'newapp-8d36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4QOlX1lIKhtlfaAviYW2NVF_ggtQIvJI',
    appId: '1:869470742871:android:e1480c1d10312b1abaf612',
    messagingSenderId: '869470742871',
    projectId: 'newapp-8d36b',
    storageBucket: 'newapp-8d36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSfIn_FxgQQAYOOKU01FixuDg3Qg92nU',
    appId: '1:869470742871:ios:425c1d53fe58eba6baf612',
    messagingSenderId: '869470742871',
    projectId: 'newapp-8d36b',
    storageBucket: 'newapp-8d36b.appspot.com',
    iosClientId: '869470742871-jhn05llsfr1p1661pb7lgtu23775s799.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSfIn_FxgQQAYOOKU01FixuDg3Qg92nU',
    appId: '1:869470742871:ios:425c1d53fe58eba6baf612',
    messagingSenderId: '869470742871',
    projectId: 'newapp-8d36b',
    storageBucket: 'newapp-8d36b.appspot.com',
    iosClientId: '869470742871-jhn05llsfr1p1661pb7lgtu23775s799.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapp',
  );
}
